[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[colors.cursor]
cursor = "#fe8019"
text = "#282828"

[colors.selection]
background = "#458588"
text = "#fbf1c7"


[font]
normal = { family = "ShureTechMono Nerd Font", style = "Regular" }
bold = { family = "ShureTechMono Nerd Font", style = "Bold" }
italic = { family = "ShureTechMono Nerd Font", style = "Italic" }
bold_italic = { family = "ShureTechMono Nerd Font", style = "Bold Italic" }
size = 11.0  # change this if you want it bigger/smaller

