#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale /home/dataman/Space/Pictures/Wallpaper/gruvbox_void_linux.png 
xsetroot -cursor_name left_ptr
picom &
polybar &
lxqt-policykit-agent &
pipewire &

 
bspc monitor -d      󰝚 󰠮   


bspc config top_padding        24
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       3
bspc config window_gap         16


bspc config split_ratio                 0.55
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc config normal_border_color   "#2e3440"
bspc config active_border_color   "#2e3440"
bspc config focused_border_color  "#5e81ac"
